### ISSUE TITLE
.Net Core 2.2 CanReadConfigFile Test is not working 

### ISSUE THREAD

**Issue by manoj-choudhari-git** [nunit/nunit3-vs-adapter-demo#10]
I tried to set this up in visual studio 2019.  The first test case works, but this test case does not work. 
I ensured that appsettings has firstKey and it has expected value, even then it is not working. 

       [Test]
        public static void CanReadConfigFile()
        {
            Assert.That(ConfigurationManager.AppSettings.Get("firstKey"), Is.EqualTo("myvalue"));
        }

**Comment by OsirisTerje** [comment]
The adapter demo is still .net fw 4.5.  I assume you have changed the project.  Can you please share it?

**Comment by OsirisTerje** [comment]
I assume you're running the NUnit3CoreTestDemo.sln, and not the Framework demo sln.  This test is not part of the core test demo, so did you add it? 
IF you ran the core demo:  The default runs under 1.1, you mention 2.2, so you did change it ?  
You also changed the test, right?
Can you please share your changes/repo ? (I assume you forked it, if you just point us to that , we can check)

**Comment by manoj-choudhari-git** [comment]
Closing it for now as not able to repro now.
